export const AUTH_ERROR_CODES = {
    NOT_ALLOWED: 'AUTH.NOT_ALLOWED',
    NOT_AUTHENTIFIED: 'AUTH.NOT_AUTHENTIFIED',
    USER_ALREADY_EXIST: 'AUTH.USER_ALREADY_EXIST',
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    SESSION_EXPIRED: 'AUTH.SESSION_EXPIRED',
    SESSION_NOT_FOUND: 'AUTH.SESSION_NOT_FOUND',
    USER_DOESNT_EXIST: 'AUTH.USER_DOESNT_EXIST',
    INVALID_AUTH_PROVIDER: 'AUTH.INVALID_AUTH_PROVIDER',
    UNAUTHORIZED_ROLE: 'AUTH.UNAUTHORIZED_ROLE',
    //OAUTH
    INVALID_EXCHANGE_CODE: 'AUTH.INVALID_EXCHANGE_CODE',
    VERIFIER_CODE_DOESNT_MATCH: 'AUTH.VERIFIER_CODE_DOESNT_MATCH',
    UNACCESSIBLE_PROVIDER_INFO: 'AUTH.UNACCESSIBLE_PROVIDER_INFO',
} as const;
